// apps/nextjs/components/comment.tsx
import Link from "next/link";

import type { IComment } from "../types";
import Toggle from "./toggle";

const Comment = (props: { comment: IComment }) => {
  return (
    <li className="comment">
      <div className="by">
        <Link href={`/users/${props.comment.user}`}>{props.comment.user}</Link>{" "}
        {props.comment.time_ago} ago
      </div>
      <div
        className="text"
        dangerouslySetInnerHTML={{ __html: props.comment.content }}
      />
      {!!props.comment.comments.length && (
        <Toggle>
          {props.comment.comments.map((comment) => (
            <Comment key={comment.id} comment={comment} />
          ))}
        </Toggle>
      )}
    </li>
  );
};

export default Comment;

// apps/sveltekit/src/lib/Comment.svelte
<script lang="ts">
	import type { Comment } from '$lib/types';

	const pluralize = (n: number) => n + (n === 1 ? ' reply' : ' replies');

	export let comment: Comment;
	let open = true;
</script>

<li class="comment">
	<div class="by">
		<a href={`/users/${comment.user}`}>{comment.user}</a>
		{comment.time_ago} ago
	</div>
	<div class="text">{@html comment.content}</div>
	{#if comment.comments.length}
		<div class="toggle" class:open>
			<a on:click={() => (open = !open)}>
				{open ? '[-]' : '[+] ' + pluralize(comment.comments.length) + ' collapsed'}
			</a>
		</div>
		{#if open}
			<ul class="comment-children">
				{#each comment.comments as Comment}
					<svelte:self {comment} />
				{/each}
			</ul>
		{/if}
	{/if}
</li>
