// apps/remix/app/components/comment.tsx
import { useState } from "react";
import { Link } from "@remix-run/react";

import type { IComment } from "../types";

const pluralize = (n: number) => n + (n === 1 ? " reply" : " replies");

const Comment = (props: { comment: IComment }) => {
  const [open, setOpen] = useState(true);

  return (
    <li className="comment">
      <div className="by">
        <Link to={`/users/${props.comment.user}`}>{props.comment.user}</Link>{" "}
        {props.comment.time_ago} ago
      </div>
      <div
        className="text"
        dangerouslySetInnerHTML={{ __html: props.comment.content }}
      />
      {props.comment.comments.length && (
        <>
          <div className={open ? "toggle open" : "toggle"}>
            <a onClick={() => setOpen(!open)}>
              {open
                ? "[-]"
                : "[+] " +
                  pluralize(props.comment.comments.length) +
                  " collapsed"}
            </a>
          </div>
          {open && (
            <ul className="comment-children">
              {props.comment.comments.map((comment) => (
                <Comment key={comment.id} comment={comment} />
              ))}
            </ul>
          )}
        </>
      )}
    </li>
  );
};

export default Comment;

// apps/sveltekit/src/lib/Comment.svelte
<script lang="ts">
	import type { Comment } from '$lib/types';

	const pluralize = (n: number) => n + (n === 1 ? ' reply' : ' replies');

	export let comment: Comment;
	let open = true;
</script>

<li class="comment">
	<div class="by">
		<a href={`/users/${comment.user}`}>{comment.user}</a>
		{comment.time_ago} ago
	</div>
	<div class="text">{@html comment.content}</div>
	{#if comment.comments.length}
		<div class="toggle" class:open>
			<a on:click={() => (open = !open)}>
				{open ? '[-]' : '[+] ' + pluralize(comment.comments.length) + ' collapsed'}
			</a>
		</div>
		{#if open}
			<ul class="comment-children">
				{#each comment.comments as Comment}
					<svelte:self {comment} />
				{/each}
			</ul>
		{/if}
	{/if}
</li>
