// apps/nextjs/components/story.tsx
import Link from "next/link";

import type { IStory } from "../types";

const Story = (props: { story: IStory }) => {
  return (
    <li className="news-item">
      <span className="score">{props.story.points}</span>
      <span className="title">
        {props.story.url && !props.story.url.startsWith("item?id=") ? (
          <>
            <a href={props.story.url} target="_blank" rel="noreferrer">
              {props.story.title}
            </a>
            <span className="host"> ({props.story.domain})</span>
          </>
        ) : (
          <Link href={`/item/${props.story.id}`}>{props.story.title}</Link>
        )}
      </span>
      <br />
      <span className="meta">
        {props.story.type !== "job" ? (
          <>
            by{" "}
            <Link href={`/users/${props.story.user}`}>{props.story.user}</Link>{" "}
            {props.story.time_ago} |{" "}
            <Link href={`/stories/${props.story.id}`}>
              {props.story.comments_count
                ? `${props.story.comments_count} comments`
                : "discuss"}
            </Link>
          </>
        ) : (
          <Link href={`/stories/${props.story.id}`}>
            {props.story.time_ago}
          </Link>
        )}
      </span>
      {props.story.type !== "link" && (
        <>
          {" "}
          <span className="label">{props.story.type}</span>
        </>
      )}
    </li>
  );
};

export default Story;

// apps/sveltekit/src/lib/Story.svelte
<script lang="ts">
	import type { Story } from '$lib/types';

	export let story: Story;
</script>

<li class="news-item">
	<span class="score">{story.points}</span>
	<span class="title">
		{#if story.url}
			<a href={story.url} target="_blank" rel="noreferrer">
				{story.title}
			</a>
			<span class="host"> ({story.domain})</span>
		{:else}
			<a href={`/stories/${story.id}`}>{story.title}</a>
		{/if}
	</span>
	<br />
	<span class="meta">
		{#if story.type !== 'job'}
			by <a href={`/users/${story.user}`}>{story.user}</a>{' '}
			{story.time_ago} |{' '}
			<a href={`/stories/${story.id}`}>
				{story.comments_count ? `${story.comments_count} comments` : 'discuss'}
			</a>
		{:else}
			<a href={`/stories/${story.id}`}>{story.time_ago}</a>
		{/if}
	</span>
	{#if story.type !== 'link'}
		{' '}
		<span class="label">{story.type}</span>
	{/if}
</li>
