// apps/solid/src/components/toggle.tsx
import { createSignal } from "solid-js";
import server$ from "solid-start/server";

export default function Toggle(props: { children: any }) {
  const [open, setOpen] = createSignal(true);

  const rpc = server$(() => {
    console.log("Hi from the server");
    return "Welcome to solid start!";
  });

  const handleClick = async () => {
    setOpen((o) => !o);
    const rpcResponse = await rpc();
    console.log({ rpcResponse });
  };

  return (
    <>
      <div class="toggle" classList={{ open: open() }}>
        <a onClick={handleClick}>{open() ? "[-]" : "[+] comments collapsed"}</a>
      </div>
      <ul
        class="comment-children"
        style={{ display: open() ? "block" : "none" }}
      >
        {props.children}
      </ul>
    </>
  );
}

// apps/nextjs/components/toggle.tsx
"use client";

import { ReactNode, useState } from "react";

export default function Toggle({ children }: { children: ReactNode }) {
  const [open, setOpen] = useState(true);

  const handleClick = async () => {
    setOpen((o) => !o);
    const serverResponse = await (await fetch("/api/demo")).json();
    console.log({ serverResponse });
  };

  return (
    <>
      <div className={"toggle" + (open ? " open" : "")}>
        <a onClick={handleClick}>{open ? "[-]" : "[+] comments collapsed"}</a>
      </div>
      <ul
        className="comment-children"
        style={{ display: open ? "block" : "none" }}
      >
        {children}
      </ul>
    </>
  );
}
