// apps/nextjs/app/stories/[id]/page.tsx
import Link from 'next/link';

import type { IStory } from '../../../types';
import Comment from '../../../components/comment';
import fetchAPI from '../../../api';

const Story = async ({ params }: { params: { id: string } }) => {
  const story: IStory = await fetchAPI(`item/${params.id}`);

  return (
    story && (
      <div className="item-view">
        <div className="item-view-header">
          <a href={story.url} target="_blank">
            <h1>{story.title}</h1>
          </a>
          {story.domain && <span className="host">({story.domain})</span>}
          <p className="meta">
            {story.points} points | by{' '}
            <Link href={`/users/${story.user}`}>{story.user}</Link>{' '}
            {story.time_ago} ago
          </p>
        </div>
        <div className="item-view-comments">
          <p className="item-view-comments-header">
            {story.comments_count
              ? story.comments_count + ' comments'
              : 'No comments yet.'}
          </p>
          <ul className="comment-children">
            {story.comments.map((comment) => (
              <Comment key={comment.id} comment={comment} />
            ))}
          </ul>
        </div>
      </div>
    )
  );
};

export default Story;

// apps/sveltekit/src/routes/stories/[id]/+page.svelte
<script lang="ts">
	import { navigating } from '$app/stores';
	import Comment from '$lib/Comment.svelte';
	import type { PageData } from './$types';

	export let data: PageData;
</script>

<svelte:head>
	<title>{data.story.title} | Svelte Hacker News</title>
</svelte:head>

{#if $navigating}
	<div class="news-list-nav">Loading...</div>
{:else}
	<div class="item-view">
		<div class="item-view-header">
			<a href={data.story.url} target="_blank" rel="noreferrer">
				<h1>{data.story.title}</h1>
			</a>
			{#if data.story.domain}
				<span class="host">({data.story.domain})</span>
			{/if}
			<p class="meta">
				{data.story.points} points | by
				<a href={`/users/${data.story.user}`}>{data.story.user}</a>
				{data.story.time_ago} ago
			</p>
		</div>
		<div class="item-view-comments">
			<p class="item-view-comments-header">
				{data.story.comments_count ? data.story.comments_count + ' comments' : 'No comments yet.'}
			</p>
			<ul class="comment-children">
				{#each data.story.comments as comment (comment.id)}
					<Comment {comment} />
				{/each}
			</ul>
		</div>
	</div>
{/if}
