// apps/sveltekit/src/routes/[...stories]/+page.svelte
<script lang="ts">
	import Story from '$lib/Story.svelte';
	import { navigating } from '$app/stores';

	/** @type {import('./$types').PageData} */
	export let data;
	export let { page, type, stories } = data;
</script>

<div class="news-view">
	{#if !$navigating}
		<div class="news-list-nav">
			{#if page > 1}
				<a class="page-link" href={`/${type}?page=${page - 1}`} aria-label="Previous Page">
					{'<'} prev
				</a>
			{:else}
				<span class="page-link disabled" aria-disabled="true">
					{'<'} prev
				</span>
			{/if}
			<span>page {page}</span>
			{#if stories && stories.length >= 29}
				<a class="page-link" href={`/${type}?page=${page + 1}`} aria-label="Next Page">
					more {'>'}
				</a>
			{:else}
				<span class="page-link disabled" aria-disabled="true">
					more {'>'}
				</span>
			{/if}
		</div>
		<main class="news-list">
			{#if stories}
				<ul>
					{#each stories as story (story.id)}
						<Story {story} />
					{/each}
				</ul>
			{/if}
		</main>
	{:else}
		<div class="news-list-nav">Loading...</div>
	{/if}
</div>

// apps/solid/src/routes/[...stories].tsx
import { Component, For, Show } from 'solid-js';
import { A, createRouteData, RouteDataArgs, useRouteData } from 'solid-start';
import Story from '~/components/story';
import fetchAPI from '~/lib/api';
import { IStory } from '~/types';

const mapStories = {
  top: 'news',
  new: 'newest',
  show: 'show',
  ask: 'ask',
  job: 'jobs',
} as const;

export const routeData = ({ location, params }: RouteDataArgs) => {
  const page = () => +location.query.page || 1;
  const type = () => (params.stories || 'top') as keyof typeof mapStories;

  const stories = createRouteData<IStory[], string>(async () => {
    return fetchAPI(`${mapStories[type()]}?page=${page()}`);
  });

  return { type, stories, page };
};

const Stories: Component = () => {
  const { page, type, stories } = useRouteData<typeof routeData>();

  return (
    <div class="news-view">
      <div class="news-list-nav">
        <Show
          when={page() > 1}
          fallback={
            <span class="page-link disabled" aria-disabled="true">
              {'<'} prev
            </span>
          }
        >
          <A
            class="page-link"
            href={`/${type()}?page=${page() - 1}`}
            aria-label="Previous Page"
          >
            {'<'} prev
          </A>
        </Show>
        <span>page {page()}</span>
        <Show
          when={stories() && stories()!.length >= 29}
          fallback={
            <span class="page-link disabled" aria-disabled="true">
              more {'>'}
            </span>
          }
        >
          <A
            class="page-link"
            href={`/${type()}?page=${page() + 1}`}
            aria-label="Next Page"
          >
            more {'>'}
          </A>
        </Show>
      </div>
      <main class="news-list">
        <Show when={stories()}>
          <ul>
            <For each={stories()}>{(story) => <Story story={story} />}</For>
          </ul>
        </Show>
      </main>
    </div>
  );
};

export default Stories;
